### ISSUE TITLE
Pre-trained models

### ISSUE THREAD

**Issue by tomaszgy** [kawu/concraft-pl#36]
Hello,

first of all, great job with Concraft v. 2.0! :-)

Are there by any chance any pre-trained models available? Or, alternatively, is there an easy way to generate them using NKJP?

Thanks in advance for help!

**Comment by kawu** [comment]
Sorry for a delay; a model pre-trained on the National Corpus of Polish is now available for download, see https://github.com/kawu/concraft-pl/tree/master#pre-trained-models.  Hope this will be useful!

**Comment by tomaszgy** [comment]
Hi Kuba,

thanks a lot for updating the docs and sharing the model - it's going to be super useful! :-)

Cheers,
Tomasz
